name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set permissions for update_paths.sh
        run: chmod +x ./scripts/update_paths.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Debug directory structure
        run: |
          echo "Current directory structure:"
          ls -R ./assets
          ls -R ./lessons

      - name: Sync assets and lessons to S3
        run: |
          # First, list existing files in S3
          echo "Existing files in S3 assets folder:"
          aws s3 ls s3://sc-course-materials/v2/assets/

          # Sync with verbose output
          aws s3 sync ./assets s3://sc-course-materials/v2/assets/ --acl public-read --no-delete
          aws s3 sync ./lessons s3://sc-course-materials/v2/lessons/ --acl public-read --no-delete

          # Verify files were uploaded
          echo "Files in S3 after sync:"
          aws s3 ls s3://sc-course-materials/v2/assets/
          aws s3 ls s3://sc-course-materials/v2/lessons/

      - name: Sync v2 to S3
        run: |
          aws s3 sync ./v2 s3://sc-course-materials/v2/ --acl public-read --delete --exclude "vendor/*"
